### ISSUE TITLE
ROI Loader does not always load individual FOVs

### ISSUE THREAD

**Issue by fdsteffen** [fractal-napari-plugins-collection/napari-ome-zarr-navigator#14]
Currently the ROI Loader does not load the FOVs individually in this dataset (https://zenodo.org/records/8322727) in contrast to our sample dataset (https://zenodo.org/records/11262587). Both FOV are loaded when selecting FOV = 1. Selecting the second FOV throws an error. @jluethi If this is not a bug in ROILoader but related to the OME-ZARR FOV table being ill-formatted, we might need to catch that error.

![napari_roi](https://github.com/user-attachments/assets/fd1b6d6d-8010-4e4e-b788-035a8cef5ef9)

**Comment by jluethi** [comment]
Likely issue here: Label array is 4D and the ROI loader doesn't handle that atm
