### ISSUE TITLE
Don't translate well position if only one image is loaded

### ISSUE THREAD

**Issue by fdsteffen** [fractal-napari-plugins-collection/napari-ome-zarr-navigator#20]
The `calculate_well_positions()` should not translate the well/FOV ROI if only one image is loaded but not a plate, because napari positions the individual image at the origin. This affects both the rectangle positioning in the image browser as well as the labels of the ROI loader.

**Comment by jluethi** [comment]
Does this happen if one starts the ROI loader directly? I thought I had this handled in a special case. Or how do you trigger the case where wells/FOVs are moved?
